disabled_rules:
  - todo
opt_in_rules:
  - force_unwrapping
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
line_length:
  - 300 # warning
  - 400 # error
force_unwrapping: error
